# Generated by Django 4.2.5 on 2023-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='currency',
            field=models.CharField(choices=[('USD', 'dollar'), ('EUR', 'euro'), ('RUB', 'ruble')], default='USD', max_length=3),
        ),
    ]
